# -*- coding: utf-8 -*-
"""Object Oriented Programming using Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KAhjatz7LLdgxKqHARtfNre0_3lJXnuK

**Problem-1**
"""

from abc import ABC, abstractmethod
class Person:
    def __init__(self, name, age, gender, address):
        self.name = name
        self.age = age
        self.gender = gender
        self.address = address

    def __str__(self):
      return (f"Name: {self.name}, Age: {self.age}, Gender: {self.gender}, Address: {self.address}")

    def greet(self):
        print(f"Hello {self.name} My name is Jane ")


    @abstractmethod
    def introduce(self):
      pass

    @staticmethod
    def is_adult(age):
      if age > 18:
        return True
      else:
        return False

class child(Person):
    def __init__(self, name, age, gender, address,student_id):
      super().__init__(name, age, gender, address)
      self.student_id = student_id

    def introduce(self):
        return f"Hi, I'm {self.name}, a student with ID {self.student_id}."

p1=child("sim",21,"f","misrod",3)
p1.is_adult(21)
p1.greet()
p1.introduce()

"""**Problem-2**"""

class Employee(Person):
  counter=0
  def __init__(self, name, age, gender, address,salary):
     super().__init__(name, age, gender, address)
     Employee.counter+=1
     self.__employee_id = f"EMP{Employee.counter}"
     self._salary=salary

  def __del__(self):
    Employee.counter-=1

  @property
  def employee_id(self):
    return self.__employee_id

  @property
  def salary(self):
      return self._salary

  @property
  def get_counter(cls):
    return cls.counter

  @salary.setter
  def salary(self,amount):
    if self.amount>=0:
      self.salary=amount
    else:
      print("salary can't be -ve")

  def salary_increase(self,amount):
    self.salary+=amount


emp1 = Employee("Alice", 30,"f","msd",5000)
print(Employee.counter)

emp2 = Employee("Bob", 25,"m","msd",100)
print(Employee.counter)
print(emp1.employee_id)
print(emp1.salary)
print(emp2.salary)

"""**Problem-3**"""

class Teacher(Employee):
    counter = 0

    def __init__(self, name, age, gender, address, salary, subjects=None):
        super().__init__(name, age, gender, address, salary)
        Teacher.counter += 1
        self.__teacher_id = f"TEC{Teacher.counter:02d}"
        self.subjects = subjects if subjects else []
    def __del__(self):
        Teacher.counter -= 1

    @property
    def teacher_id(self):
        return self.__teacher_id

    @property
    def get_counter(cls):
        return cls.counter

    def add_subject(self, subject):
        if subject not in self.subjects:
            self.subjects.append(subject)

    def remove_subject(self, subject):
        if subject in self.subjects:
            self.subjects.remove(subject)

    def introduce(self):
        return f"Hi, I'm {self.name}, a teacher with ID {self.teacher_id}. I teach: {', '.join(self.subjects) if self.subjects else 'No subjects assigned yet.'}"

    @property
    def employee_id(self):
        raise AttributeError("Teacher object has no attribute 'employee_id'")

teacher1 = Teacher("simran", 35, "F", "Indi", 70000, ["Math", "Science"])

print(teacher1.teacher_id)
print(teacher1.subjects)
print(teacher1.name)
print(teacher1.salary)
print(teacher1.introduce())